# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5415a2d97286a47b259a2b13707fc82f"
name = "fwn-arystan-2"
handle = "fwn-arystan-2"
application_url = "https://broadband-valuable-pas-argue.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://broadband-valuable-pas-argue.trycloudflare.com/auth/callback",
  "https://broadband-valuable-pas-argue.trycloudflare.com/auth/shopify/callback",
  "https://broadband-valuable-pas-argue.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
