# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1635834a813b89b95822784db1ca869"
name = "fwn-ilya-google"
application_url = "https://shopifyfwnautomation.fly.dev"
embedded = true
[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopifyfwnautomation.fly.dev/auth/callback",
  "https://shopifyfwnautomation.fly.dev/auth/shopify/callback",
  "https://shopifyfwnautomation.fly.dev/api/auth/callback"
]

[pos]
embedded = false
